# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8de6afef378f167b95b3a5a2e3ee70e2"
name = "ConciliAI"
application_url = "https://concilia-six.vercel.app/"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://concilia-six.vercel.app/api/auth/shopify",
  "https://concilia-six.vercel.app/api/auth/shopify/callback"
]
